---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: store-aws-ebs-fe
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  encrypted: "true"
  kmsKeyId: ""
allowVolumeExpansion: true
