---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: store-aws-ebs-fixicc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  encrypted: "true"
  kmsKeyId: ""
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
